version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/plantuml
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: docker buildx build
          command: |
            docker context create tls-env
            docker buildx create tls-env --use
            ./build-and-test-multi-arch-circleci.sh
      - run: ./test-multi-arch-circleci.sh
      - run: ./build-and-test-docker.sh
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./deploy-artifacts.sh
          when: on_success
  test-arm64:
    machine:
      image: ubuntu-2004:202101-01
      resource_class: arm.medium
    working_directory: ~/plantuml
    steps:
      - checkout
      - run: ./test-multi-arch-circleci.sh
workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build
      - test-intel:
          requires:
            - build
      - test-arm64:
          requires:
            - build
