version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/plantuml
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: docker buildx build
          command: |
            docker context create tls-env
            docker buildx create tls-env --use
            ./build-and-push-multi-arch-circleci.sh
  test-intel:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: ~/plantuml
    steps:
      - checkout
      - run: ./test-multi-arch-circleci.sh
  test-arm64:
    machine:
      image: ubuntu-2004:202101-01
      resource_class: arm.medium
    working_directory: ~/plantuml
    steps:
      - checkout
      - run: ./test-multi-arch-circleci.sh
  deploy:
    docker:
      - image: cimg/base:stable
    working_directory: ~/plantuml
    steps:
      - checkout
      - run:
          command: ./deploy-artifacts.sh
workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build:
          context:
            - publishing
      - test-intel:
          requires:
            - build
      - test-arm64:
          requires:
            - build
      - deploy:
          context:
            - publishing
          requires:
            - test-arm64
            - test-intel
