version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/plantuml
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
    steps:
      - checkout
      - run:
          name: Install buildx
          command: |
            # https://circleci.com/blog/building-docker-images-for-multiple-os-architectures/

            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64"

            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"

            mkdir -p ~/.docker/cli-plugins

            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx

            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
            # Need this to prevent: error: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
            docker buildx create --use
      - run: ./build-and-push-docker.sh
  test-intel:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/plantuml
    steps:
      - checkout
      - run: ./test-docker.sh
  test-arm64:
    machine:
      image: ubuntu-2004:202101-01
      resource_class: arm.medium
    working_directory: ~/plantuml
    steps:
      - checkout
      - run: ./test-docker.sh
  deploy:
    machine:
      image: ubuntu-2004:202010-01
      resource_class: arm.medium
    working_directory: ~/plantuml
    steps:
      - checkout
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./deploy-artifacts.sh
          when: on_success
workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - build
      - test-intel:
          requires:
            - build
      - test-arm64:
          requires:
            - build
      - deploy:
          requires:
            - test-intel
            - test-arm64
