version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/plantuml
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: |
          docker context create tls-env
          docker buildx create tls-env --use
          ./build-and-test-multi-arch-circleci.sh
      - run: ./build-and-test-docker.sh
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./deploy-artifacts.sh
          when: on_success
