version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    working_directory: ~/plantuml
    steps:
      - checkout
      - run:
          command: |
            # Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=plantuml%3Alatest&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied

            if [[ "$CIRCLE_SHELL_ENV"  =~ "localbuild"  ]] ;  then

              echo sudo chown root /usr/bin/docker
              sudo chown root /usr/bin/docker

              sudo chmod u+s /usr/bin/docker
            fi
      - setup_remote_docker:
          version: 20.10.11
      - run: |
          # First problem: error: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
          docker buildx create --use
          #
          ./build-and-test-multi-arch-locally.sh
      - run: ./build-and-test-docker.sh
      - run:
          name: Publish artifacts
          command: |
            TERM=dumb ./deploy-artifacts.sh
          when: on_success
